language: python

python: 
    - "3.6"

#install dependencies
#before_install: cd qns_api

install:
    - pip install -r requirements.txt

scripts:
    - cd qns_api
    - pytest tests
    - coverage report

after_success:
    - coveralls
