language: python

python: 
    - "3.6"

#install dependencies
before_install: cd qns_api

install:
    - pip install -r requirements.txt

scripts:
    - nosetests --with-coverage --cover-package=app
    - coverage report

after_success:
    - coveralls
