language: python

python: 
    - "3.6"

#install dependencies
#before_install: cd qns_api

install:
    - pip install -r requirements.txt

script:
    - pytest qns_api/tests --cov=qns_api/api --cov-report term-missing


after_success:
    - coveralls
